#!/bin/sh
set -eu

cat > /usr/share/nginx/html/env.js <<EOF
window.__TECNOTITLAN_ENV__ = {
  REACT_APP_API_URL: "${REACT_APP_API_URL:-}",
  REACT_APP_STRIPE_PUBLISHABLE_KEY: "${REACT_APP_STRIPE_PUBLISHABLE_KEY:-}",
  REACT_APP_SENTRY_DSN: "${REACT_APP_SENTRY_DSN:-}",
  REACT_APP_SENTRY_ENVIRONMENT: "${REACT_APP_SENTRY_ENVIRONMENT:-production}",
  REACT_APP_SENTRY_TRACES_SAMPLE_RATE: "${REACT_APP_SENTRY_TRACES_SAMPLE_RATE:-0.05}",
  REACT_APP_RELEASE: "${REACT_APP_RELEASE:-}",
  REACT_APP_SITE_URL: "${REACT_APP_SITE_URL:-https://www.tecnotitlan.com.mx}"
};
EOF
