services:
  backend: # Nombre del servicio
    build: # Configuración de la construcción de la imagen
      context: . # El contexto es la carpeta donde está docker-compose.yml (d:\Tecnotitlan)
      dockerfile: Dockerfile # El Dockerfile está en la raíz del contexto (d:\Tecnotitlan\Dockerfile)
    ports: # Mapeo de puertos
      - "5000:5000" # Expone el puerto 5000 del contenedor al puerto 5000 del host
    env_file: # Archivo de variables de entorno
      - ./.env # La ruta al .env es relativa a este archivo docker-compose.yml
    restart: always # Reinicia el contenedor si falla
