services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tecnotitlan_backend
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - whatsapp_auth:/app/auth_info_baileys
      - uploads:/app/uploads
    networks:
      - tecnotitlan-net

  n8n:
    image: n8nio/n8n:latest
    container_name: tecnotitlan_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - ./.env
    environment:
      - GENERIC_TIMEZONE=America/Mexico_City
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - tecnotitlan-net

networks:
  tecnotitlan-net:

volumes:
  n8n_data:
  whatsapp_auth:
  uploads:
