import React, { useEffect, useState } from 'react';
import api from '../../services/apiService';
import styles from './ServiceQualityScreen.module.css';
import { useRealtimeRefresh } from '../../hooks/useRealtimeRefresh';

const sourceLabels = { WHATSAPP: 'WhatsApp', SUPPORT: 'Soporte', MELI_QUESTION: 'Pregunta ML', MELI_POST_SALE: 'Posventa ML', MELI_CLAIM: 'Reclamo ML', TECATL: 'Tecatl' };
const initialTemplate = { name: '', sourceType: '', category: 'GENERAL', body: '' };
const initialReview = { clarity: 5, empathy: 5, accuracy: 5, resolution: 5, compliance: 5, notes: '' };

const ServiceQualityScreen = () => {
  const [data, setData] = useState({ summary: {}, byChannel: {}, alerts: [], reviews: [] });
  const [templates, setTemplates] = useState([]); const [form, setForm] = useState(initialTemplate);
  const [reviewTarget, setReviewTarget] = useState(null); const [review, setReview] = useState(initialReview);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const load = async () => { try { const [dashboard, templateData] = await Promise.all([api.get('/service-quality/dashboard'), api.get('/service-quality/templates?all=true')]); setData(dashboard.data.data); setTemplates(templateData.data.data.templates || []); } catch (err) { setError(err.response?.data?.message || 'No se pudo cargar calidad de servicio.'); } };
  useRealtimeRefresh(['quality', 'inbox', 'messages'], load);
  useEffect(() => { load(); const timer = window.setInterval(load, 300000); return () => clearInterval(timer); }, []);
  const run = async (request, message) => { setBusy(true); setError(''); setSuccess(''); try { await request(); await load(); setSuccess(message); return true; } catch (err) { setError(err.response?.data?.message || 'No se pudo completar la operación.'); return false; } finally { setBusy(false); } };
  const createTemplate = async (event) => { event.preventDefault(); const ok = await run(() => api.post('/service-quality/templates', form), 'Plantilla creada.'); if (ok) setForm(initialTemplate); };
  const saveReview = async (event) => { event.preventDefault(); if (!reviewTarget) return; const ok = await run(() => api.post(`/service-quality/reviews/${reviewTarget.sourceType}/${encodeURIComponent(reviewTarget.sourceId)}`, review), 'Evaluación de calidad guardada.'); if (ok) { setReviewTarget(null); setReview(initialReview); } };
  const s = data.summary || {};
  return <div className={styles.page}><header><div><span>Operación medible</span><h1>SLA y calidad de servicio</h1><p>Anticipa vencimientos, estandariza respuestas y mide atención real.</p></div><button onClick={() => run(() => api.post('/service-quality/alerts/scan'), 'Alertas SLA actualizadas.')} disabled={busy}><i className="fas fa-bell" /> Revisar SLA ahora</button></header>{error && <div className={styles.error}>{error}</div>}{success && <div className={styles.success}>{success}</div>}
    <section className={styles.stats}><article><small>SLA cumplido</small><strong>{s.compliance == null ? '—' : `${s.compliance}%`}</strong></article><article><small>Por vencer</small><strong>{s.atRisk || 0}</strong></article><article><small>Vencidos</small><strong>{s.breached || 0}</strong></article><article><small>Primera respuesta</small><strong>{s.avgFirstResponseMinutes == null ? '—' : `${s.avgFirstResponseMinutes} min`}</strong></article><article><small>Calidad promedio</small><strong>{s.averageQuality == null ? '—' : `${s.averageQuality}/5`}</strong></article></section>
    <section className={styles.grid}><article><h2>Rendimiento por canal</h2><div className={styles.table}>{Object.entries(data.byChannel || {}).map(([channel, metric]) => <div key={channel}><b>{channel}</b><span>{metric.compliance == null ? 'Sin muestra' : `${metric.compliance}% SLA`}</span><span>{metric.avgFirstResponseMinutes == null ? '—' : `${metric.avgFirstResponseMinutes} min`}</span><em>{metric.breached} vencidos</em></div>)}</div></article><article><h2>Alertas activas</h2><div className={styles.alerts}>{data.alerts?.length ? data.alerts.map((item) => <button key={item.id} onClick={() => setReviewTarget(item)}><span><b>{item.sla.state === 'BREACHED' ? 'Vencido' : 'Por vencer'} · {item.channel}</b><small>{item.title}</small></span><em>{Math.abs(item.sla.remainingMinutes)} min</em></button>) : <p>Sin alertas activas.</p>}</div></article></section>
    {reviewTarget && <form className={styles.review} onSubmit={saveReview}><div><h2>Evaluar: {reviewTarget.title}</h2><button type="button" onClick={() => setReviewTarget(null)}>Cerrar</button></div><section>{['clarity','empathy','accuracy','resolution','compliance'].map((field) => <label key={field}>{({clarity:'Claridad',empathy:'Empatía',accuracy:'Exactitud',resolution:'Resolución',compliance:'Cumplimiento'})[field]}<select value={review[field]} onChange={(e) => setReview({...review,[field]:Number(e.target.value)})}>{[1,2,3,4,5].map((score) => <option key={score}>{score}</option>)}</select></label>)}</section><textarea rows="3" value={review.notes} onChange={(e) => setReview({...review,notes:e.target.value})} placeholder="Hallazgos y oportunidad de mejora..." /><button disabled={busy}>Guardar evaluación</button></form>}
    <section className={styles.templates}><div><h2>Plantillas de respuesta</h2><p>Variables permitidas: {'{{customer_name}}'}, {'{{order_number}}'}, {'{{agent_name}}'} y {'{{agent_note}}'}.</p></div><form onSubmit={createTemplate}><input required placeholder="Nombre" value={form.name} onChange={(e) => setForm({...form,name:e.target.value})} /><select value={form.sourceType} onChange={(e) => setForm({...form,sourceType:e.target.value})}><option value="">Todos los canales</option>{Object.entries(sourceLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><input placeholder="Categoría" value={form.category} onChange={(e) => setForm({...form,category:e.target.value})} /><textarea required rows="3" placeholder="Texto de la plantilla" value={form.body} onChange={(e) => setForm({...form,body:e.target.value})} /><button disabled={busy}>Crear plantilla</button></form><div className={styles.templateList}>{templates.map((template) => <article key={template.id}><div><b>{template.name}</b><small>{template.category} · {sourceLabels[template.sourceType] || 'Todos'}</small></div><p>{template.body}</p><button onClick={() => run(() => api.put(`/service-quality/templates/${template.id}`, { isActive: !template.isActive }), template.isActive ? 'Plantilla pausada.' : 'Plantilla activada.')}>{template.isActive ? 'Pausar' : 'Activar'}</button></article>)}</div></section>
  </div>;
};
export default ServiceQualityScreen;
